// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzzbilwsouyryuroobxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6emJpbHdzb3V5cnl1cm9vYnhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDU2NTksImV4cCI6MjA2MDAyMTY1OX0.pw2acnJXc3y8IdC8i4CAgWTrn5otEAk-haruV9-Z2rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);